# Configuration for Discovery Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=true

# Properties for JWT
jwt.auth-gen.secret-key=9nY1Q3yXqZpX4zv5u8k2m1r7w4h9t6y3p0a5b8c2d1f6g7h8i9j0k1l2m3n4o5p
jwt.auth-gen.accessKey.expirationTimeInSeconds=86400
jwt.auth-gen.refreshKey.expirationTimeInSeconds=604800

# Configuration for Tomcat Server
server.port=8082

# Configuration for Spring Data JPA
spring.datasource.url=jdbc:mysql://localhost:3306/users_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
