# MySQl configuration for prod
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/tms
spring.datasource.username=root
spring.datasource.password=root


# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Use "update" initially (till schema is fixed) so tables get created from entities
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
